-- BuildingData.lua
-- Defines every purchasable building for the city simulation.
-- Categories: Residential, Commercial, Industrial, Services, Infrastructure, Farm
--
-- Each entry:
--   cost        : purchase price in coins
--   plotCost    : cost to buy the land plot first
--   income      : coins generated per minute (0 = none)
--   population  : residents added
--   happiness   : happiness delta (-5 to +10)
--   safety      : crime-reduction points (police/fire)
--   health      : health points (hospitals etc.)
--   education   : education points (schools)
--   power       : power supplied (+) or consumed (-)
--   water       : water supplied (+) or consumed (-)
--   color       : BrickColor name for the building pad
--   icon        : emoji shown in UI
--   description : flavour text

local BuildingData = {}

-- ── Plot ─────────────────────────────────────────────────────────────────
BuildingData.PlotCost = 500   -- flat cost to unlock any empty plot

-- ── Buildings ─────────────────────────────────────────────────────────────
BuildingData.Buildings = {

	-- ── RESIDENTIAL ──────────────────────────────────────────────────────
	SmallHouse = {
		category    = "Residential",
		displayName = "Small House",
		cost        = 800,
		income      = 12,
		population  = 4,
		happiness   = 2,
		safety      = 0,
		health      = 0,
		education   = 0,
		power       = -1,
		water       = -1,
		color       = "Bright yellow",
		icon        = "🏠",
		description = "A cosy home for a small family.",
	},
	MediumHouse = {
		category    = "Residential",
		displayName = "Medium House",
		cost        = 1800,
		income      = 25,
		population  = 8,
		happiness   = 3,
		safety      = 0,
		health      = 0,
		education   = 0,
		power       = -2,
		water       = -2,
		color       = "Bright orange",
		icon        = "🏡",
		description = "A comfortable house for a growing family.",
	},
	Apartment = {
		category    = "Residential",
		displayName = "Apartment Block",
		cost        = 5000,
		income      = 80,
		population  = 30,
		happiness   = 1,
		safety      = 0,
		health      = 0,
		education   = 0,
		power       = -5,
		water       = -4,
		color       = "Sand blue",
		icon        = "🏢",
		description = "High-density housing for many residents.",
	},
	Mansion = {
		category    = "Residential",
		displayName = "Mansion",
		cost        = 15000,
		income      = 200,
		population  = 6,
		happiness   = 8,
		safety      = 0,
		health      = 0,
		education   = 0,
		power       = -4,
		water       = -3,
		color       = "Bright blue",
		icon        = "🏰",
		description = "Luxury living — boosts city happiness.",
	},

	-- ── COMMERCIAL ───────────────────────────────────────────────────────
	Shop = {
		category    = "Commercial",
		displayName = "Shop",
		cost        = 1200,
		income      = 40,
		population  = 0,
		happiness   = 2,
		safety      = 0,
		health      = 0,
		education   = 0,
		power       = -2,
		water       = -1,
		color       = "Bright green",
		icon        = "🏪",
		description = "A local shop — earns steady retail income.",
	},
	Market = {
		category    = "Commercial",
		displayName = "Market",
		cost        = 3000,
		income      = 90,
		population  = 0,
		happiness   = 4,
		safety      = 0,
		health      = 0,
		education   = 0,
		power       = -3,
		water       = -2,
		color       = "Bright yellowish-green",
		icon        = "🛒",
		description = "A busy marketplace — great foot traffic.",
	},
	Mall = {
		category    = "Commercial",
		displayName = "Shopping Mall",
		cost        = 12000,
		income      = 300,
		population  = 0,
		happiness   = 6,
		safety      = 0,
		health      = 0,
		education   = 0,
		power       = -8,
		water       = -4,
		color       = "Hot pink",
		icon        = "🛍",
		description = "The city's retail crown jewel.",
	},
	Bank = {
		category    = "Commercial",
		displayName = "Bank",
		cost        = 8000,
		income      = 180,
		population  = 0,
		happiness   = 1,
		safety      = 2,
		health      = 0,
		education   = 0,
		power       = -3,
		water       = -1,
		color       = "Gold",
		icon        = "🏦",
		description = "Generates high income and funds the economy.",
	},

	-- ── INDUSTRIAL ───────────────────────────────────────────────────────
	Factory = {
		category    = "Industrial",
		displayName = "Factory",
		cost        = 4000,
		income      = 120,
		population  = 0,
		happiness   = -3,
		safety      = 0,
		health      = -2,
		education   = 0,
		power       = -6,
		water       = -3,
		color       = "Dark grey",
		icon        = "🏭",
		description = "High income but reduces happiness and health.",
	},
	Warehouse = {
		category    = "Industrial",
		displayName = "Warehouse",
		cost        = 2000,
		income      = 55,
		population  = 0,
		happiness   = -1,
		safety      = 0,
		health      = 0,
		education   = 0,
		power       = -2,
		water       = -1,
		color       = "Medium stone grey",
		icon        = "🏗",
		description = "Storage and logistics centre.",
	},

	-- ── SERVICES ─────────────────────────────────────────────────────────
	PoliceStation = {
		category    = "Services",
		displayName = "Police Station",
		cost        = 3500,
		income      = 0,
		population  = 0,
		happiness   = 3,
		safety      = 15,
		health      = 0,
		education   = 0,
		power       = -3,
		water       = -1,
		color       = "Bright blue",
		icon        = "🚔",
		description = "Reduces crime, improves safety rating.",
	},
	FireStation = {
		category    = "Services",
		displayName = "Fire Station",
		cost        = 3000,
		income      = 0,
		population  = 0,
		happiness   = 2,
		safety      = 10,
		health      = 2,
		education   = 0,
		power       = -2,
		water       = -3,
		color       = "Bright red",
		icon        = "🚒",
		description = "Protects the city from fires.",
	},
	Hospital = {
		category    = "Services",
		displayName = "Hospital",
		cost        = 6000,
		income      = 0,
		population  = 0,
		happiness   = 5,
		safety      = 0,
		health      = 20,
		education   = 0,
		power       = -5,
		water       = -5,
		color       = "White",
		icon        = "🏥",
		description = "Vital for city health and happiness.",
	},
	School = {
		category    = "Services",
		displayName = "School",
		cost        = 4000,
		income      = 0,
		population  = 0,
		happiness   = 4,
		safety      = 2,
		health      = 0,
		education   = 15,
		power       = -3,
		water       = -2,
		color       = "Bright yellow",
		icon        = "🏫",
		description = "Raises education and future income potential.",
	},
	University = {
		category    = "Services",
		displayName = "University",
		cost        = 12000,
		income      = 50,
		population  = 0,
		happiness   = 5,
		safety      = 2,
		health      = 0,
		education   = 35,
		power       = -6,
		water       = -4,
		color       = "Sand red",
		icon        = "🎓",
		description = "Boosts education and generates research income.",
	},
	Park = {
		category    = "Services",
		displayName = "Park",
		cost        = 1500,
		income      = 0,
		population  = 0,
		happiness   = 8,
		safety      = 1,
		health      = 3,
		education   = 1,
		power       = 0,
		water       = -1,
		color       = "Bright green",
		icon        = "🌳",
		description = "Green space — biggest happiness boost per coin.",
	},
	Stadium = {
		category    = "Services",
		displayName = "Stadium",
		cost        = 20000,
		income      = 150,
		population  = 0,
		happiness   = 12,
		safety      = 0,
		health      = 2,
		education   = 0,
		power       = -10,
		water       = -6,
		color       = "Bright blue",
		icon        = "🏟",
		description = "Massive happiness and event income.",
	},

	-- ── INFRASTRUCTURE ────────────────────────────────────────────────────
	PowerPlant = {
		category    = "Infrastructure",
		displayName = "Power Plant",
		cost        = 5000,
		income      = 30,
		population  = 0,
		happiness   = -2,
		safety      = 0,
		health      = -1,
		education   = 0,
		power       = 40,
		water       = -4,
		color       = "Bright red",
		icon        = "⚡",
		description = "Provides +40 power to the city grid.",
	},
	SolarFarm = {
		category    = "Infrastructure",
		displayName = "Solar Farm",
		cost        = 8000,
		income      = 20,
		population  = 0,
		happiness   = 2,
		safety      = 0,
		health      = 1,
		education   = 0,
		power       = 25,
		water       = 0,
		color       = "Bright blue",
		icon        = "🌞",
		description = "Clean energy — no happiness penalty.",
	},
	WaterTower = {
		category    = "Infrastructure",
		displayName = "Water Tower",
		cost        = 3000,
		income      = 15,
		population  = 0,
		happiness   = 0,
		safety      = 0,
		health      = 3,
		education   = 0,
		power       = -2,
		water       = 30,
		color       = "Cyan",
		icon        = "💧",
		description = "Supplies +30 water to the city.",
	},
	Road = {
		category    = "Infrastructure",
		displayName = "Road",
		cost        = 200,
		income      = 0,
		population  = 0,
		happiness   = 1,
		safety      = 0,
		health      = 0,
		education   = 0,
		power       = 0,
		water       = 0,
		color       = "Dark grey",
		icon        = "🛣",
		description = "Connects city zones and improves traffic flow.",
	},

	-- ── FARM (extends the farming theme) ─────────────────────────────────
	Greenhouse = {
		category    = "Farm",
		displayName = "Greenhouse",
		cost        = 2500,
		income      = 60,
		population  = 0,
		happiness   = 2,
		safety      = 0,
		health      = 2,
		education   = 0,
		power       = -3,
		water       = -4,
		color       = "Transparent",
		icon        = "🌿",
		description = "Year-round crop production, high water use.",
	},
	Windmill = {
		category    = "Farm",
		displayName = "Windmill",
		cost        = 1800,
		income      = 35,
		population  = 0,
		happiness   = 3,
		safety      = 0,
		health      = 1,
		education   = 0,
		power       = 10,
		water       = 0,
		color       = "White",
		icon        = "🌬",
		description = "Rustic icon that generates power and income.",
	},
	Silo = {
		category    = "Farm",
		displayName = "Grain Silo",
		cost        = 1200,
		income      = 45,
		population  = 0,
		happiness   = 0,
		safety      = 0,
		health      = 0,
		education   = 0,
		power       = -1,
		water       = 0,
		color       = "Bright orange",
		icon        = "🌾",
		description = "Stores grain and earns steady commodity income.",
	},
}

-- ── Category ordering for UI ──────────────────────────────────────────────
BuildingData.Categories = {
	"Residential", "Commercial", "Industrial",
	"Services", "Infrastructure", "Farm",
}

-- ── City simulation tick (seconds between income payouts) ─────────────────
BuildingData.IncomeTick = 60   -- every 60 seconds

-- ── Starting city stats ───────────────────────────────────────────────────
BuildingData.StartStats = {
	population  = 0,
	happiness   = 50,   -- out of 100
	safety      = 0,
	health      = 0,
	education   = 0,
	power       = 0,    -- net (supply - demand)
	water       = 0,
}

return BuildingData
